name: Add Entry to Tech Radar
description: Request to add an Entry to the Tech Radar.
title: "[TR Entry]: "
assignees:
  - copilot
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: What is the name of the entry?
      placeholder: ex. Micronaut
    validations:
      required: true
  - type: dropdown
    id: ring
    attributes:
      label: Ring
      description: What ring does this entry fall in?
      options:
        - adopt
        - trial
        - assess (Default)
        - hold
      default: 2
    validations:
      required: true
  - type: dropdown
    id: quadrant
    attributes:
      label: Quadrant
      description: What quadrant does this entry fall in?
      options:
        - languages-and-frameworks (Default)
        - methods-and-patterns
        - platforms-and-operations
        - tools
      default: 0
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma separated filter tags for this entry?
      placeholder: ex. platform, ios, frontend
    validations:
      required: true
  - type: textarea
    id: entry-description
    attributes:
      label: Description of Entry record
      description: Please provide a description of why this entry is placed here?
    validations:
      required: true
